### PR TITLE
add ibm jdk8 to docker image

### PR DESCRIPTION
**Pull request by phil-mcgee**
Add an install-ibm-jdk8.sh script and call it from the Dockerfile, including defining environment variable

### CODE REVIEW

**Comment by gilday** [comment]
Note that this Dockerfile is a public, automated build on Docker Hub; therefore, this change will add the IBM JDK to a public Docker image we own.

Are we allowed to redistribute the IBM JDK like this? If not, we will need to move this Docker image off of Docker Hub and make it an image that we use internally.

**Comment by gilday** [comment]
As of Java 1.8, are Eclipse OpenJ9 and IBM Java the same thing? https://hub.docker.com/r/adoptopenjdk/openjdk8-openj9

**Comment by phil-mcgee** [comment]
I thought the Contrast Organization on DockerHub was a private space, but I see I can read it without signing in – Rats!

Guess I need to see if I can configure pipelines to pull images from jfrog.

I’ll check IBM’s license first, but it’s not likely to be very permissive.

**Comment by phil-mcgee** [comment]
> As of Java 1.8, are Eclipse OpenJ9 and IBM Java the same thing? https://hub.docker.com/r/adoptopenjdk/openjdk8-openj9

I think J9 is a JVM without a class library so it needs to be bundled with OpenJDK class libraries to create a useful platform.

**Pull request closed without merging**
